export enum ActivityAction {
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_OVERDUE = "TASK_OVERDUE",
  TASK_DELETED = "TASK_DELETED",
  TASK_DELETED_PERMANENTLY = "TASK_DELETED_PERMANENTLY",
  TASK_RESTORED = "TASK_RESTORED",
  TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED",
  TASK_REMARK_CHANGED = "TASK_REMARK_CHANGED",
  TASK_COMPLETED = "TASK_COMPLETED",
}
