export enum NotificationType {
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_OVERDUE = "TASK_OVERDUE",
  TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED",
  TASK_REMARK_CHANGED = "TASK_REMARK_CHANGED",
}
